# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rasta.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brasta.proto\x12\x03sci\"\x1c\n\tSciPacket\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x32\x37\n\x05Rasta\x12.\n\x06Stream\x12\x0e.sci.SciPacket\x1a\x0e.sci.SciPacket\"\x00(\x01\x30\x01\x42\x34Z2github.com/deislabs/akri/rasta-extensibility/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rasta_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/deislabs/akri/rasta-extensibility/proto'
  _SCIPACKET._serialized_start=20
  _SCIPACKET._serialized_end=48
  _RASTA._serialized_start=50
  _RASTA._serialized_end=105
# @@protoc_insertion_point(module_scope)
